//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1Folder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTags
    {
        public long PostId { get; set; }
        public string Tag { get; set; }
    
        public virtual Posts Posts { get; set; }
    }
}
