//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1Folder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribes
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long FollowingId { get; set; }
        public System.DateTime Date { get; set; }
        public bool isActive { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
